// Enhanced usage stats UI loaded after common.js.
(function(){
const C=['#4a90d9','#50b36b','#f5a623','#d0021b','#9013fe','#00a6a6','#8b572a','#7ed321','#9b9b9b'];
function e(t,s,css){const n=document.createElement(t);if(s!==undefined&&s!==null)n.textContent=String(s);if(css)n.style.cssText=css;return n}
function z(n){if(n)while(n.firstChild)n.removeChild(n.firstChild)}
function st(m){const a=Object.entries(m||{}).sort((x,y)=>(y[1]||0)-(x[1]||0));return a.length?a.map(([k,v])=>`${k}:${v}`).join(' '):'—'}
function mt(a,b){for(const[k,v]of Object.entries(b||{}))a[k]=(a[k]||0)+(v||0)}
function ft(ts){if(!ts)return'—';try{return new Date(ts*1000).toLocaleString('zh-CN',{hour12:false})}catch(_){return String(ts)}}
function set(id,v){const n=document.getElementById(id);if(n)n.textContent=String(v)}
function ensureTable(){let c=document.getElementById('usageBucketTableContainer');if(c)return c;const usage=document.getElementById('usageTab');const modelTable=document.getElementById('usageModelsTable');const modelCard=modelTable?modelTable.closest('div[style]'):null;const p=modelCard&&modelCard.parentNode?modelCard.parentNode:usage;if(!p)return null;c=e('div',null,'background:#fff;border:1px solid #e0e0e0;border-radius:8px;padding:16px;margin-bottom:16px;');c.id='usageBucketTableContainer';const title=e('h4','时间-模型明细','margin-top:0;color:#495057;');title.id='usageBucketTableTitle';const box=e('div',null,'overflow-x:auto;max-height:420px;overflow-y:auto;');const table=e('table',null,'width:100%;border-collapse:collapse;font-size:13px;');const thead=e('thead');const tr=e('tr',null,'background:#f8f9fa;text-align:left;');['时间','模型','成功','失败','总次数','失败率','状态码分布'].forEach(x=>tr.appendChild(e('th',x,'padding:8px;border-bottom:2px solid #dee2e6;')));const tb=e('tbody');tb.id='usageBucketTableBody';thead.appendChild(tr);table.appendChild(thead);table.appendChild(tb);box.appendChild(table);c.appendChild(title);c.appendChild(box);if(modelCard)p.insertBefore(c,modelCard);else p.appendChild(c);return c}
function renderBucketTable(t){ensureTable();const title=document.getElementById('usageBucketTableTitle');const tb=document.getElementById('usageBucketTableBody');if(!tb)return;z(tb);if(title)title.textContent=(t.bucket_type==='hour')?'时间-模型明细（今日按小时）':'时间-模型明细（按日期）';const rows=(t.series||[]).filter(x=>(x.total_calls||0)>0).sort((a,b)=>String(a.bucket||'').localeCompare(String(b.bucket||''))||((b.total_calls||0)-(a.total_calls||0)));if(!rows.length){const tr=e('tr');const td=e('td','暂无时间-模型明细数据','text-align:center;color:#999;padding:16px;');td.colSpan=7;tr.appendChild(td);tb.appendChild(tr);return}rows.forEach(r=>{const tr=e('tr',null,'border-bottom:1px solid #eee;');[r.bucket||r.date_key||'—',r.model||'unknown',r.success_calls||0,r.failure_calls||0,r.total_calls||0,`${r.failure_rate||0}%`,st(r.status_codes)].forEach((v,i)=>{const td=e('td',v,i===1?'padding:8px;font-family:monospace;':'padding:8px;');if(i===2)td.style.color='#28a745';if(i===3)td.style.color='#dc3545';if(i===4)td.style.fontWeight='bold';if(i===6)td.style.fontSize='12px';tr.appendChild(td)});tb.appendChild(tr)})}
function renderModels(models){const h=[...document.querySelectorAll('h4')].find(x=>x.textContent&&x.textContent.trim()==='模型明细');if(h)h.textContent='模型汇总（当前范围）';const tb=document.getElementById('usageModelsTableBody');if(!tb)return;z(tb);if(!models||!models.length){const tr=e('tr');const td=e('td','暂无模型调用数据','text-align:center;color:#999;padding:16px;');td.colSpan=7;tr.appendChild(td);tb.appendChild(tr);return}models.forEach(m=>{const tr=e('tr',null,'border-bottom:1px solid #eee;');[m.model,m.success_calls||0,m.failure_calls||0,m.total_calls||0,`${m.failure_rate||0}%`,ft(m.last_called_at),st(m.status_codes)].forEach((v,i)=>{const td=e('td',v,i===0?'padding:8px;font-family:monospace;':'padding:8px;');if(i===1)td.style.color='#28a745';if(i===2)td.style.color='#dc3545';if(i===3)td.style.fontWeight='bold';if(i>4)td.style.fontSize='12px';tr.appendChild(td)});tb.appendChild(tr)})}
function prep(t){const buckets=t.buckets||t.dates||[];const bm={};const mtot={};buckets.forEach(b=>bm[b]={total:0,success:0,failure:0,models:{}});(t.series||[]).forEach(p=>{const b=p.bucket||p.date_key,m=p.model||'unknown',tot=p.total_calls||0;if(!bm[b])bm[b]={total:0,success:0,failure:0,models:{}};if(!bm[b].models[m])bm[b].models[m]={total:0,success:0,failure:0,codes:{}};const it=bm[b].models[m];it.total+=tot;it.success+=p.success_calls||0;it.failure+=p.failure_calls||0;mt(it.codes,p.status_codes||{});bm[b].total+=tot;bm[b].success+=p.success_calls||0;bm[b].failure+=p.failure_calls||0;mtot[m]=(mtot[m]||0)+tot});const top=Object.keys(mtot).filter(m=>mtot[m]>0).sort((a,b)=>mtot[b]-mtot[a]).slice(0,8);return{buckets,bm,top}}
function renderChart(t){const c=document.getElementById('usageChart');if(!c)return;z(c);const d=prep(t||{});if(!d.buckets.length||!d.buckets.some(b=>d.bm[b]&&d.bm[b].total>0)){c.appendChild(e('p','暂无调用数据','text-align:center;color:#999;padding:20px;'));renderBucketTable(t||{});return}const max=Math.max(1,...d.buckets.map(b=>d.bm[b].total||0));const chart=e('div',null,'display:flex;align-items:flex-end;gap:10px;min-height:280px;overflow-x:auto;padding:20px 8px 8px;border-bottom:1px solid #eee;');d.buckets.forEach(b=>{const info=d.bm[b];const col=e('div',null,'display:flex;flex-direction:column;align-items:center;justify-content:flex-end;min-width:38px;height:260px;');col.appendChild(e('div',info.total?info.total:'','font-size:10px;color:#333;height:14px;'));const bar=e('div',null,'width:28px;height:220px;display:flex;flex-direction:column-reverse;justify-content:flex-start;background:#f2f2f2;border-radius:4px;overflow:hidden;');const lines=[`时间: ${b}`,`总次数: ${info.total}`,`成功: ${info.success}  失败: ${info.failure}`,'---'];let other={total:0,success:0,failure:0,codes:{}};const seg=[];Object.entries(info.models).forEach(([m,it])=>{if(d.top.includes(m))seg.push([m,it]);else{other.total+=it.total||0;other.success+=it.success||0;other.failure+=it.failure||0;mt(other.codes,it.codes)}});if(other.total>0)seg.push(['其他',other]);seg.sort((x,y)=>(y[1].total||0)-(x[1].total||0));seg.forEach(([m,it],i)=>{lines.push(`${m}: 成功${it.success||0} 失败${it.failure||0} 总${it.total||0}`);const s=e('div');s.title=lines.join('\n');s.style.cssText=`height:${Math.max(1,(it.total/max)*220)}px;background:${C[i%C.length]};width:100%;`;bar.appendChild(s)});bar.title=lines.join('\n');col.appendChild(bar);col.appendChild(e('div',b,'font-size:10px;color:#666;margin-top:6px;white-space:nowrap;'));chart.appendChild(col)});const legend=e('div',null,'margin-top:10px;line-height:1.8;');d.top.forEach((m,i)=>{const item=e('span',null,'display:inline-flex;align-items:center;margin-right:12px;font-size:12px;');item.appendChild(e('span',null,`display:inline-block;width:10px;height:10px;background:${C[i%C.length]};border-radius:2px;margin-right:4px;`));item.appendChild(document.createTextNode(String(m)));legend.appendChild(item)});c.appendChild(chart);c.appendChild(legend);renderBucketTable(t||{})}
window.onUsageRangeChange=function(){const s=document.getElementById('usageRangeSelect');if(!s)return;AppState.usageRange=s.value||'7d';window.refreshUsageStats()};
window.onUsageModeChange=function(){const s=document.getElementById('usageModeSelect');if(!s)return;AppState.usageMode=s.value||'all';window.refreshUsageStats()};
window.refreshUsageStats=async function(){const rs=document.getElementById('usageRangeSelect'),ms=document.getElementById('usageModeSelect');const range=(rs&&rs.value)||AppState.usageRange||'7d',mode=(ms&&ms.value)||AppState.usageMode||'all';AppState.usageRange=range;AppState.usageMode=mode;const params=`range=${encodeURIComponent(range)}&mode=${encodeURIComponent(mode)}`;const loading=document.getElementById('usageLoading');try{if(loading)loading.style.display='block';const[ar,br,cr]=await Promise.all([fetch(`./usage/summary?${params}`,{headers:getAuthHeaders()}),fetch(`./usage/timeseries?${params}`,{headers:getAuthHeaders()}),fetch(`./usage/models?${params}`,{headers:getAuthHeaders()})]);if([ar,br,cr].some(r=>r.status===401)){showStatus('认证失败，请重新登录','error');setTimeout(()=>location.reload(),1500);return}const a=await ar.json(),b=await br.json(),c=await cr.json();const sum=a.success&&a.data?a.data:{total_calls:0,success_calls:0,failure_calls:0,failure_rate:0,model_count:0};const ts=b.success&&b.data?b.data:{buckets:[],dates:[],models:[],series:[]};const models=c.success&&c.data?c.data:[];AppState.usageSummaryData=sum;AppState.usageTimeseriesData=ts;AppState.usageModelsData=models;set('usageTotal',sum.total_calls||0);set('usageSuccess',sum.success_calls||0);set('usageFailure',sum.failure_calls||0);set('usageFailureRate',`${sum.failure_rate||0}%`);set('usageModelCount',sum.model_count||0);set('totalApiCalls',sum.total_calls||0);set('totalFiles',sum.model_count||0);set('avgCallsPerFile',sum.model_count?((sum.total_calls||0)/sum.model_count).toFixed(1):'0');renderChart(ts);renderModels(models);showStatus(`已加载调用统计（${range} / ${mode}），共 ${sum.model_count||0} 个模型`,'success')}catch(err){showStatus(`网络错误: ${err.message}`,'error')}finally{if(loading)loading.style.display='none'}};
window.renderUsageChart=renderChart;window.renderUsageModelsTable=renderModels;
})();
